// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnzKf4sKyTwBgyb4SVsZue_6ALKZTnLcc',
    appId: '1:1029899466296:web:90c050c733ff43c58318cd',
    messagingSenderId: '1029899466296',
    projectId: 'warmindoapp-f7577',
    authDomain: 'warmindoapp-f7577.firebaseapp.com',
    storageBucket: 'warmindoapp-f7577.firebasestorage.app',
    measurementId: 'G-56L49NF9BG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC79Jk3XDDAECOmGUYHVDXBIHFs7IFEU2c',
    appId: '1:1029899466296:android:b41ffd17efafa8d58318cd',
    messagingSenderId: '1029899466296',
    projectId: 'warmindoapp-f7577',
    storageBucket: 'warmindoapp-f7577.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJFubwApvpykiANVkSdmR6eP8D-3wKHi0',
    appId: '1:1029899466296:ios:e65f02654318a6348318cd',
    messagingSenderId: '1029899466296',
    projectId: 'warmindoapp-f7577',
    storageBucket: 'warmindoapp-f7577.firebasestorage.app',
    iosBundleId: 'com.example.warmindoApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJFubwApvpykiANVkSdmR6eP8D-3wKHi0',
    appId: '1:1029899466296:ios:e65f02654318a6348318cd',
    messagingSenderId: '1029899466296',
    projectId: 'warmindoapp-f7577',
    storageBucket: 'warmindoapp-f7577.firebasestorage.app',
    iosBundleId: 'com.example.warmindoApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnzKf4sKyTwBgyb4SVsZue_6ALKZTnLcc',
    appId: '1:1029899466296:web:7b720dcae362589e8318cd',
    messagingSenderId: '1029899466296',
    projectId: 'warmindoapp-f7577',
    authDomain: 'warmindoapp-f7577.firebaseapp.com',
    storageBucket: 'warmindoapp-f7577.firebasestorage.app',
    measurementId: 'G-5QGHFPHWQF',
  );

}